name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t html-docker-example .

      - name: Run Docker container
        run: docker run -d -p 80:80 --name html-app html-docker-example

      - name: Test the application
        run: |
          sleep 5 # Esperar a que el contenedor esté listo
          curl -s http://localhost:80 | grep "Bienvenido al Proyecto HTML con Docker"